### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ServerBSvvv** [Solaree/C-Lib-Patcher#1]
how to use a "compile.py" ?
![image](https://github.com/Solaree/C-Lib-Patcher/assets/77868876/d91920a3-f79a-485d-94ea-eb4f904566c4)

**Comment by ServerBSvvv** [comment]
new problem
![image](https://github.com/Solaree/C-Lib-Patcher/assets/77868876/8f27a400-592a-4073-8da9-78f04032b346)

**Comment by Solaree** [comment]
> new problem ![image](https://user-images.githubusercontent.com/77868876/267104712-8f27a400-592a-4073-8da9-78f04032b346.png)

its not code problem, you must use clang toolchain from android ndk

**Comment by ServerBSvvv** [comment]
do i need to install android studio and ndk?

> > new problem ![image](https://user-images.githubusercontent.com/77868876/267104712-8f27a400-592a-4073-8da9-78f04032b346.png)
> 
> its not code problem, you must use clang toolchain from android ndk

**Comment by Solaree** [comment]
> how to use a "compile.py" ? ![image](https://user-images.githubusercontent.com/77868876/267101982-d91920a3-f79a-485d-94ea-eb4f904566c4.png)

for example, 
```python compile.py --clang --shared mempatch```

**Comment by ServerBSvvv** [comment]
> > how to use a "compile.py" ? ![image](https://user-images.githubusercontent.com/77868876/267101982-d91920a3-f79a-485d-94ea-eb4f904566c4.png)
> 
> for example, `python compile.py --clang --shared mempatch`

so do I need to install android studio and ndk?

**Comment by Solaree** [comment]
> > > how to use a "compile.py" ? ![image](https://user-images.githubusercontent.com/77868876/267101982-d91920a3-f79a-485d-94ea-eb4f904566c4.png)
> > 
> > for example, `python compile.py --clang --shared mempatch`
> 
> so do I need to install android studio and ndk?

No, just install ndk toolchain using official installation methods

**Comment by ServerBSvvv** [comment]
> > > > how to use a "compile.py" ? ![image](https://user-images.githubusercontent.com/77868876/267101982-d91920a3-f79a-485d-94ea-eb4f904566c4.png)
> > > 
> > > 
> > > for example, `python compile.py --clang --shared mempatch`
> > 
> > 
> > so do I need to install android studio and ndk?
> 
> No, just install ndk toolchain using official installation methods

can you please provide a link to ndktoolchain? I just can't find these official installation methods
and what operating system should I use it on?

**Comment by ServerBSvvv** [comment]
а ну всё я уже нашел, спасибо за приятное время провождение-общение с тобой! а я пойду устанавливать ubuntu второй системой... если мне опять (надеюсь нет) понадобится помощь я опять напишу issue!

**Comment by ServerBSvvv** [comment]
и да спасибо за помощь
